### ISSUE TITLE
Minus double-negates

### ISSUE THREAD

**Issue by technomancy** [meric/l2l#13] opened 2015-11-21 07:23 UTC
Witness the output of compiling a subtraction:

```lua
-- (let (a 1 b 2 c (- b a)) c)
local _var0
do
   local a=1
   local b=2
   local _var4
   _var4=(-b)
   local _var6
   local _var7
   for _var6, _var7 in next, {a} do
      _var4 = _var4 - _var7
   end
   local c=_var4
   _var0=c
end
return _var0
```

**Comment by meric** [comment] 2015-11-21 14:53
Regression from resolving #7

**Comment by meric** [comment] 2015-11-21 15:06
That particular example compiles like that because the is_variadic function incorrectly said `b` was variadic. (function calls, `...` are variadic, but single symbols should not be). As a result, only a was passed as the non-variadic `parameters` part of the compile_subtract function, which (incorrectly) assumes the call is unary, when only one non-variadic parameter passed. 

I can't figure out how to get the function to work out whether the call is unary or not unary, correctly, when  it is called like `(- (function call that may return 1 or two values))`. The compiler can't actually know how many arguments until its evaluated. It could be one value, in that case it should be unary, or it could be more than one value, and in that case it shouldn't be unary. 

Perhaps we should remove the compile_subtract and implement as a function.

**Comment by meric** [comment] 2015-11-21 15:15
For now to fix the bug immediately, let's remove the unary part of `-` and `/` first. I think lua's variadic argument mechanics doesn't mesh with traditional lisps' well.

**Comment by meric** [comment] 2015-11-21 16:10
For now I've documented removing unary mode for these two operators, in 565edf727f1697807ca4a301630e82988419415b.

**Closed by meric** 2015-11-21 16:10 UTC
